OgrenciYonetimSistemi/Models/Helper/Mesajlar/ChatDetayGetir.cs
using OgrenciYonetimSistemi.Models.SqlModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OgrenciYonetimSistemi.Models.Helper
{
	public class ChatDetayGetir
	{
        public List<SP_YazismaDetayGetir_Result> YazismaDetayListesi { get; set; }
        public List<SP_YazismaListesiGetir_Result> YazismaListesi { get; set; }
        public List<SP_YeniMesajKullaniciListesiGetir_Result> YeniMesajKullaniciListesi { get; set; }

    }
}

OgrenciYonetimSistemi/Models/Helper/Mesajlar/ChatSohbetGecmisiGetir.cs
using OgrenciYonetimSistemi.Models.SqlModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OgrenciYonetimSistemi.Models.Helper
{
	public class ChatSohbetGecmisiGetir
    {
        public List<SP_YazismaDetayGetir_Result> YazismaDetayListesi { get; set; }

    }
}

OgrenciYonetimSistemi/Models/Helper/Mesajlar/UstMesajlariGetir.cs
using OgrenciYonetimSistemi.Models.SqlModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OgrenciYonetimSistemi.Models.Helper
{
    public class UstMesajlariGetir
    {

        public List<SP_YazismaListesiGetir_Result> YazismaListesi { get; set; }
        public int? OkunmayanMesajSayisi { get; set; }



    }
}

OgrenciYonetimSistemi/Models/Mesajlar.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciYonetimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesajlar
    {
        public int Id { get; set; }
        public string Icerik { get; set; }
        public int AliciUye_Id { get; set; }
        public bool Statu { get; set; }
        public int Kullanici_Id { get; set; }
        public System.DateTime KayitTarihi { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
    }
}

OgrenciYonetimSistemi/Models/SqlModel/Mesajlar.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciYonetimSistemi.Models.SqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesajlar
    {
        public int Id { get; set; }
        public string Icerik { get; set; }
        public int AliciUye_Id { get; set; }
        public bool Statu { get; set; }
        public int Kullanici_Id { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public bool OkunduMu { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
    }
}

OgrenciYonetimSistemi/Controllers/MesajlarController.cs
using OgrenciYonetimSistemi.Models.Filters;
using OgrenciYonetimSistemi.Models.Helper;
using OgrenciYonetimSistemi.Models.Helper.Kullanıcı;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static OgrenciYonetimSistemi.Models.Helper.Kullanıcı.KullaniciEnum;

namespace OgrenciYonetimSistemi.Controllers
{
    [CustomAuthenticationFilter]
    public class MesajlarController : BaseController
    {

        public ActionResult Index(int? Id)
        {
            ViewData["MesajDetayiIstenilenUye_Id"] = Id.HasValue ? Id.Value : 0;

            ChatDetayGetir model = new ChatDetayGetir()
            {
                YazismaListesi = db.SP_YazismaListesiGetir(LoginUser.Kullanici_Id).ToList(),
                YeniMesajKullaniciListesi = db.SP_YeniMesajKullaniciListesiGetir(LoginUser.Role_Id).ToList()
            };

            return View(model);

        }


        public ActionResult _sohbetDetaylariGetir(int? SohbetGecmisiIstenilenUye_Id)
        {
            ViewData["Uye_Id"] = SohbetGecmisiIstenilenUye_Id;
            ChatDetayGetir model = new ChatDetayGetir()
            {
                YazismaDetayListesi = db.SP_YazismaDetayGetir(SohbetGecmisiIstenilenUye_Id, LoginUser.Kullanici_Id).ToList()
            };
            return PartialView("_sohbetDetaylariGetir", model);
        }

        public ActionResult _sohbetGecmisiListeGetir()
        {
            ChatDetayGetir model = new ChatDetayGetir()
            {
                YazismaListesi = db.SP_YazismaListesiGetir(LoginUser.Kullanici_Id).ToList(),
            };
            return PartialView("_sohbetGecmisiListeGetir", model);
        }

        public ActionResult _ustMesajlariGetir()
        {
            int okunmayanMesajAdet = db.Mesajlar.Where(x => x.AliciUye_Id == LoginUser.Kullanici_Id && x.OkunduMu == false && x.Statu == true).Count();

            UstMesajlariGetir model = new UstMesajlariGetir()
            {
                YazismaListesi = (from _okunmayanMesajListe in db.SP_YazismaListesiGetir(LoginUser.Kullanici_Id)
                                  where _okunmayanMesajListe.OkunmamisMesajSayisi > 0
                                  orderby _okunmayanMesajListe.KayitTarihi descending
                                  select _okunmayanMesajListe
                                  ).Take(3).ToList(),


                OkunmayanMesajSayisi = okunmayanMesajAdet
            };
            return PartialView("_ustMesajlariGetir", model);
        }





        [HttpPost]
        public JsonResult MesajGonder(string Mesaj, int? AliciUye_Id)
        {
            try
            {

                if (string.IsNullOrEmpty(Mesaj))
                {
                    ResultData.message = "Mesaj alanı boş olamaz.";
                    ResultData.status = false;
                    return Json(ResultData);
                }
                if (!(AliciUye_Id > 0))
                {
                    ResultData.message = "Lütfen Mesaj atılacak kişiyi seçiniz.";
                    ResultData.status = false;
                    return Json(ResultData);
                }

                var mesaj = db.SP_MesajGonder(AliciUye_Id, Mesaj, LoginUser.Kullanici_Id).FirstOrDefault();
                if (mesaj.Status == true)
                {
                    ResultData = new Models.Helper.Result.ResultObject
                    {
                        data = mesaj,
                        status = true
                    };
                    return Json(ResultData);
                }
            }
            catch (Exception ex)
            {

                logger.Error(ex, "Hata");
                ResultData = new Models.Helper.Result.ResultObject
                {
                    message = "İşleminiz sırasında istisna ile karşılaşıldı.",
                    status = false
                };
            }
            return Json(ResultData);
        }

        [HttpPost]
        public JsonResult MesajOkundu(int? mesajGonderenUye_Id)
        {
            try
            {
                var mesaj = db.SP_MesajOkundu(LoginUser.Kullanici_Id, mesajGonderenUye_Id).FirstOrDefault();
                if (mesaj.Status == true)
                {
                    ResultData = new Models.Helper.Result.ResultObject
                    {
                        data = mesaj,
                        status = true
                    };
                    return Json(ResultData);
                }
            }
            catch (Exception ex)
            {
                logger.Error(ex, "Hata");
                ResultData = new Models.Helper.Result.ResultObject
                {
                    message = "İşleminiz sırasında istisna ile karşılaşıldı.",
                    status = false
                };
            }
            return Json(ResultData);
        }



        [HttpPost]
        public JsonResult TopluMesajGonder(string Mesaj)
        {
            try
            {
                if (string.IsNullOrEmpty(Mesaj))
                {
                    ResultData.message = "Mesaj alanı boş olamaz.";
                    ResultData.status = false;
                    return Json(ResultData);
                }
              
                var mesaj = db.SP_TopluMesajGonder(LoginUser.Kullanici_Id, Mesaj).FirstOrDefault();
                if (mesaj.Status == true)
                {
                    ResultData = new Models.Helper.Result.ResultObject
                    {
                        data = mesaj,
                        status = true
                    };
                    return Json(ResultData);
                }
            }
            catch (Exception ex)
            {

                logger.Error(ex, "Hata");
                ResultData = new Models.Helper.Result.ResultObject
                {
                    message = "İşleminiz sırasında istisna ile karşılaşıldı.",
                    status = false
                };
            }
            return Json(ResultData);
        }




    }

}

OgrenciYonetimSistemi/Views/Mesajlar/Index.cshtml
@model OgrenciYonetimSistemi.Models.Helper.ChatDetayGetir
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/css/BootstrapChat.css" rel="stylesheet" />

@Html.Hidden("MesajDetayiIstenilenUye_Id", ViewData["MesajDetayiIstenilenUye_Id"])

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">

                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <section class="col-lg-12 connectedSortable">

                    <!-- DIRECT CHAT -->
                    <div class="card direct-chat direct-chat-primary">
                        <div class="card-header">
                            <h3 class="card-title">Yazışmalarım</h3>

                            <div class="card-tools">
                             
                                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                    <i class="fas fa-minus"></i>
                                </button>

                                <button type="button" class="btn btn-tool" data-card-widget="remove">
                                    <i class="fas fa-times"></i>
                                </button>


                            </div>

                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">

                            <div id="topluMesajGonder" aria-hidden="true">
                                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Toplu Mesaj İletimi</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <form id="topluMesajGonder">
                                                    <div class="col-sm-12">
                                                        <label for="message-text" class="col-form-label">Mesaj:</label>
                                                        <textarea class="form-control" name="mesaj" required="required" title="Mesaj boş geçilemez." id="mesaj"></textarea>
                                                    </div>

                                                </form><a</a>   
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">İptal</button>
                                                <button type="button" class="btn btn-primary" onclick="TopluMesajGonder(this)">Gönder</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="container">
                                <div class="row clearfix">
                                    <div class="col-lg-12">

                                        <div class="container">
                                            <h3 class=" text-center">Yazışmalarım</h3>

                                            <div class="messaging">
                                                <div class="inbox_msg">
                                                    <div class="inbox_people">
                                                        <ul class="nav nav-tabs" id="myTab" role="tablist">
                                                            <li class="nav-item">
                                                                <a class="nav-link active" id="home-tab" data-toggle="tab" href="#sohbetGecmisi" role="tab" aria-controls="sohbetGecmisi" aria-selected="true">Yazışmalar</a>
                                                            </li>
                                                            <li class="nav-item">
                                                                <a class="nav-link" id="profile-tab" data-toggle="tab" href="#yeniMesaj" role="tab" aria-controls="yeniMesaj" aria-selected="false">Yeni Mesaj</a>
                                                            </li>

                                                            <li class="nav-item">
                                                                <a class="nav-link" id="topluMesajModal">Toplu Mesaj</a>
                                                            </li>

                                                        </ul>
                                                        <div class="tab-content" id="myTabContent">
                                                            <div class="tab-pane fade show active" id="sohbetGecmisi" role="tabpanel" aria-labelledby="sohbetGecmisi-tab">

                                                                <div class="headind_srch">
                                                                    <div class="recent_heading">
                                                                        <h4>Sohbet Geçmişi</h4>
                                                                    </div>
                                                                    <div class="srch_bar">
                                                                        <div class="stylish-input-group">
                                                                            <input type="text" class="search-bar" placeholder="Search" id="sohbetGecmisiAra">
                                                                            <span class="input-group-addon">
                                                                                <button type="button"> <i class="fa fa-search" aria-hidden="true"></i> </button>
                                                                            </span>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <div class="inbox_chat sohbetGecmisiListe">

                                                                    @*chat listesi refresh*@






                                                                </div>
                                                            </div>
                                                            <div class="tab-pane fade" id="yeniMesaj" role="tabpanel" aria-labelledby="yeniMesaj-tab">

                                                                <div class="headind_srch">
                                                                    <div class="recent_heading">
                                                                        <h4>Yeni Mesaj</h4>
                                                                    </div>
                                                                    <div class="srch_bar">
                                                                        <div class="stylish-input-group">
                                                                            <input type="text" class="search-bar" placeholder="Search" id="yeniMesajAra">
                                                                            <span class="input-group-addon">
                                                                                <button type="button"> <i class="fa fa-search" aria-hidden="true"></i> </button>
                                                                            </span>
                                                                        </div>
                                                                    </div>
                                                                </div>


                                                                <div class="inbox_chat yeniMesajListe">
                                                                    @foreach (var item in Model.YeniMesajKullaniciListesi)
                                                                    {
                                                                        <div class="chat_list" id="@item.Kullanici_Id">
                                                                            <div class="chat_people">
                                                                                <div class="chat_img"> <img src="~/Content/images/user-profile.png" alt="sunil"> </div>
                                                                                <div class="chat_ib">
                                                                                    <h5>@item.AdiSoyadi </h5>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                    }




                                                                </div>
                                                            </div>

                                                        </div>

                                                    </div>

                                                    <div class="mesgs">
                                                        <div class="msg_history">

                                                            <div class="alert alert-info" role="alert">
                                                                Yazışmak istediğiniz kişiyi seçiniz.
                                                            </div>
                                                            @*chat detay*@


                                                        </div>
                                                        <div class="type_msg" style="margin-top:20px;">
                                                            <div class="input_msg_write">
                                                                <input type="text" class="write_msg" placeholder="Type a message" />

                                                                <button class="msg_send_btn" type="button">
                                                                    <i class="fas fa-paper-plane"></i>
                                                                </button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>



                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>


                        </div>

                    </div>

                </section>

            </div>

        </div>
    </section>

</div>


@section scripts{

    <script src="~/Scripts/CustomScripts/Mesajlar.js"></script>

}

OgrenciYonetimSistemi/Views/Mesajlar/_sohbetDetaylariGetir.cshtml
@model  OgrenciYonetimSistemi.Models.Helper.ChatDetayGetir


<div style="display:none;" class="SohbetEdilecekUye" id="@ViewData["Uye_Id"]"></div>
@foreach (var yazismaDetay in Model.YazismaDetayListesi)
{
    if (yazismaDetay.MesajKonum == "R")
    {

        <div class="outgoing_msg">
            <div class="sent_msg">
                <p>
                    @yazismaDetay.Icerik
                </p>
                <span class="time_date"> @yazismaDetay.KayitTarihi</span>
            </div>
        </div>
    }
    else
    {
        <div class="incoming_msg">
            <div class="incoming_msg_img"> <img src="~/Content/images/user-profile.png" alt="sunil"> </div>

            <div class="received_msg">
                <div class="received_withd_msg">
                    <p>
                        @yazismaDetay.Icerik
                    </p>
                    <span class="time_date"> @yazismaDetay.KayitTarihi</span>
                </div>
            </div>
        </div>
    }
}

OgrenciYonetimSistemi/Views/Mesajlar/_sohbetGecmisiGetir.cshtml
@model   OgrenciYonetimSistemi.Models.Helper.ChatSohbetGecmisiGetir


@foreach (var yazismaDetay in Model.YazismaDetayListesi)
{
    if (yazismaDetay.MesajKonum == "R")
    {

        <div class="outgoing_msg">
            <div class="sent_msg">
                <p>
                    @yazismaDetay.Icerik
                </p>
                <span class="time_date"> @yazismaDetay.KayitTarihi</span>
            </div>
        </div>
    }
    else
    {
        <div class="incoming_msg">
            <div class="incoming_msg_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
            <div class="received_msg">
                <div class="received_withd_msg">
                    <p>
                        @yazismaDetay.Icerik
                    </p>
                    <span class="time_date"> @yazismaDetay.KayitTarihi</span>
                </div>
            </div>
        </div>
    }
}

OgrenciYonetimSistemi/Views/Mesajlar/_sohbetGecmisiListeGetir.cshtml
@model  OgrenciYonetimSistemi.Models.Helper.ChatDetayGetir



@foreach (var yazisma in Model.YazismaListesi)
{

    string active_chat_Class = yazisma.sira == 1 ? "chat_list active_chat" : "chat_list";

    <div class="chat_list" id="@yazisma.MesajlasilanUye_Id" onclick="sohbetDetaylariGetir('@yazisma.MesajlasilanUye_Id'),mesajOkunmaKontrol(this);">
        @Html.Hidden("OkunmayanMesajAdet", yazisma.OkunmamisMesajSayisi)
        <div class="chat_people">
            <div class="chat_img"> <img src="~/Content/images/user-profile.png" alt="sunil"> </div>
            <div class="chat_ib">

                <h5>@yazisma.MesajlasilanUyeAdiSoyadi</h5>

                @if (yazisma.Icerik.Length > 55)
                {
                    <p id="mesaj"> @Html.Raw(yazisma.Icerik.Substring(0, 55))..</p>
                }
                else
                {
                    <p id="mesaj">@yazisma.Icerik</p>
                }

                <p style="font-size: 9px; margin-left: 275px; position: absolute;"> @yazisma.KayitTarihi</p>


            </div>
        </div>
    </div>
}

OgrenciYonetimSistemi/Views/Mesajlar/_ustMesajlariGetir.cshtml
@model  OgrenciYonetimSistemi.Models.Helper.UstMesajlariGetir


<a class="nav-link" data-toggle="dropdown" href="#">
    <i class="far fa-comments"></i>
    @if (@Model.OkunmayanMesajSayisi > 0)
    {
        <span class="badge badge-danger navbar-badge">@Model.OkunmayanMesajSayisi  </span>
    }
    else
    {
        <span class="badge badge-danger navbar-badge"></span>
    }
</a>




<div class="dropdown-menu dropdown-menu-lg dropdown-menu-right" id="sohbetGecmisiListe">
    @if (Model.OkunmayanMesajSayisi == 0)
    {
    <div class="dropdown-item dropdown-footer">
        <p style="font-size: 13px;"> Okunmamış yazışmanız bulunmamaktadır.</p>
        <div class="dropdown-divider"></div>
    </div>
    }

    @foreach (var yazismaDetay in Model.YazismaListesi)
    {
        <a href="#" onclick="mesajDetayiGetir('@yazismaDetay.MesajlasilanUye_Id'),ustMesajOkunmaKontrol(this)" class="dropdown-item" id="@yazismaDetay.MesajlasilanUye_Id">
            <!-- Message Start -->
            @Html.Hidden("OkunmayanMesajAdet", yazismaDetay.OkunmamisMesajSayisi)
            <div class="media">
                <img src="~/Content/images/user-profile.png" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                <div class="media-body">
                    <h3 class="dropdown-item-title">
                        @yazismaDetay.MesajlasilanUyeAdiSoyadi
                    </h3>

                    @if (yazismaDetay.Icerik.Length > 15)
                    {
                        <p> @Html.Raw(yazismaDetay.Icerik.Substring(0, 15))..</p>
                    }
                    else
                    {
                        <p>@yazismaDetay.Icerik</p>
                    }
                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> @yazismaDetay.MesajGecenSure</p>
                </div>
            </div>
            <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
    }
    <a href="@Url.Action("Index","Mesajlar")" class="dropdown-item dropdown-footer">Bütün Mesajları Göster</a>

</div>